/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package flip_flop_db;

import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;

/**
 *
 * @author nouma
 */
public class SignUp_Frame extends javax.swing.JFrame {

    /**
     * Creates new form SignUp_Frame
     */
    public SignUp_Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sign_username = new javax.swing.JLabel();
        sign_pass = new javax.swing.JLabel();
        sign_uder_text = new javax.swing.JTextField();
        sign_pass_feild = new javax.swing.JPasswordField();
        setTitle("SingUp Form");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setResizable(false);
        jLabel1 = new javax.swing.JLabel();
        create_button = new javax.swing.JButton();
        back_to_login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sign_username.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        sign_username.setText("Username");

        sign_pass.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        sign_pass.setText("Password");

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel1.setText("Create Account");

        create_button.setText("Register");
        create_button.setBackground(Color.BLACK);
        create_button.setForeground(Color.RED);

        create_button.setFont(new java.awt.Font("Dialog", 0, 18));
        create_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_buttonActionPerformed(evt);
            }
        });

        back_to_login.setText("Login");
        back_to_login.setBackground(Color.BLACK);
        back_to_login.setForeground(Color.RED);

        back_to_login.setFont(new java.awt.Font("Dialog", 0, 18));
        back_to_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_to_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(create_button, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(back_to_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sign_username)
                                    .addComponent(sign_pass))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sign_pass_feild)
                                    .addComponent(sign_uder_text, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel1)))
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sign_username)
                    .addComponent(sign_uder_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sign_pass)
                    .addComponent(sign_pass_feild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(create_button)
                    .addComponent(back_to_login))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void create_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_buttonActionPerformed
        // TODO add your handling code here:
        String username = sign_uder_text.getText();
        String password = new String(sign_pass_feild.getPassword());

        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(SignUp_Frame.this,
                    "Please enter both username and password",
                    "Registration Error",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            if (insertUser(username, password)) {
                JOptionPane.showMessageDialog(SignUp_Frame.this,
                        "User created successfully",
                        "Registration Successful",
                        JOptionPane.INFORMATION_MESSAGE);
                dispose(); // Close the sign-up frame
                Login_Frame loginFrame = new Login_Frame();
                loginFrame.setVisible(true); // Open the login frame
            } else {
                JOptionPane.showMessageDialog(SignUp_Frame.this,
                        "User already exists",
                        "Registration Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_create_buttonActionPerformed

    private void back_to_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_to_loginActionPerformed
        // TODO add your handling code here:
        dispose(); // Close the sign-up frame
        Login_Frame loginFrame = new Login_Frame();
        loginFrame.setVisible(true); // Open the login frame
    }//GEN-LAST:event_back_to_loginActionPerformed
    private boolean insertUser(String username, String password) {
        java.sql.Connection conn = null;
        java.sql.PreparedStatement pstmt = null;
        ResultSet rs = null;

        try {
            // Load MySQL JDBC Driver
            Class.forName("com.mysql.cj.jdbc.Driver");

            // Define Connection URL
            String url = "jdbc:mysql://localhost:3306/flip"; // Replace with your database name
            String user = "root"; // Replace with your MySQL username
            String pass = ""; // Replace with your MySQL password

            // Open a connection
            conn = DriverManager.getConnection(url, user, pass);


            
            String checkUserQuery = "SELECT COUNT(*) FROM user_table WHERE username = ?";
            pstmt = conn.prepareStatement(checkUserQuery);
            pstmt.setString(1, username);
            rs = pstmt.executeQuery();
            rs.next();
            int count = rs.getInt(1);
            if (count > 0) {
                // User already exists
                return false;
            } else {
                // Insert the new user
                String insertUserQuery = "INSERT INTO user_table (username, password) VALUES (?, ?)";
                pstmt = conn.prepareStatement(insertUserQuery);
                pstmt.setString(1, username);
                pstmt.setString(2, password);
                int rowsAffected = pstmt.executeUpdate();
                return rowsAffected > 0; // Return true if rows were affected (i.e., user was inserted successfully)
            }
        } catch (SQLException | ClassNotFoundException e) {
            e.printStackTrace(); // Handle the exception
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
                if (pstmt != null) {
                    pstmt.close();
                }
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException e) {
                e.printStackTrace(); // Handle the exception
            }
        }
        return false; // Return false if any exception occurs
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_to_login;
    private javax.swing.JButton create_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel sign_pass;
    private javax.swing.JPasswordField sign_pass_feild;
    private javax.swing.JTextField sign_uder_text;
    private javax.swing.JLabel sign_username;
    // End of variables declaration//GEN-END:variables
}
